routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('/', function () {
//     return view('welcome');
// });

Route::match(array('GET', 'POST'), '/', 'WebController@index'); #login
Route::get('/logout', 'WebController@logout');

Route::group(['prefix' => 'dokter'], function () {
    #
    Route::get('/', 'DokterController@index');
    #
    Route::get('/antrian', 'DokterController@antrian');
    Route::get('/antrian-ajax', 'DokterController@antrianAjax');
    #
    Route::get('/daftar-data-pasien', 'DokterController@daftarDataPasien');
    #
    Route::get('/rekam-medis/{pasien_id}', 'DokterController@rekamMedis');
    #
    Route::get('/form-imunisasi-ajax/{pasien_id}', 'DokterController@formImunisasiAjax');
    Route::post('/imunisasi-simpan/{pasien_id}', 'DokterController@imunisasiSimpan');
    #
    Route::post('/pemeriksaan-simpan/{pasien_id}', 'DokterController@pemeriksaanSimpan');
    #
    Route::get('/riwayat-pemeriksaan-ajax/{pasien_id}', 'DokterController@riwayatPemeriksaanAjax');
    Route::get('/riwayat-imunisasi-ajax/{pasien_id}', 'DokterController@riwayatImunisasiAjax');
    Route::get('/riwayat-antropometri-ajax/{pasien_id}', 'DokterController@riwayatAntropometriAjax');
    Route::get('/riwayat-kesehatan-ajax/{pasien_id}', 'DokterController@riwayatKesehatanAjax');

    #
    Route::match(array('GET', 'POST'), '/profile', 'DokterController@profile');

    #
    Route::get('/jenis-imunisasi', 'DokterController@jenisImunisasi');
    Route::match(array('GET', 'POST'), '/jenis-imunisasi-tambah', 'DokterController@jenisImunisasiTambah');
    Route::match(array('GET', 'POST'), '/jenis-imunisasi-edit/{imunisasi_id}', 'DokterController@jenisImunisasiEdit');
    Route::get('/jenis-imunisasi-hapus/{imunisasi_id}', 'DokterController@jenisImunisasiHapus');
});

Route::group(['prefix' => 'apoteker'], function () {
    Route::get('/', 'ApotekerController@index');
    #
    Route::get('/set-selesai/{antrian_id}', 'ApotekerController@antrianSetSelesai');
    #
    Route::get('/antrian', 'ApotekerController@antrian');
    Route::get('/antrian-ajax', 'ApotekerController@antrianAjax');
    #
    Route::get('/detail-resep-ajax/{pasien_id}/{jenis}', 'ApotekerController@resepDetail');
    // Route::get('/resep-detail', 'ApotekerController@resepDetail');
    #
    Route::get('/cetak-resep/{pasien_id}/{jenis}', 'ApotekerController@cetakResep');
    #
    Route::match(array('GET', 'POST'), '/profile', 'ApotekerController@profile');

    #
    Route::get('/obat', 'ApotekerController@obat');
    Route::match(array('GET', 'POST'), '/obat-tambah', 'ApotekerController@obatTambah');
    Route::match(array('GET', 'POST'), '/obat-edit/{obat_id}', 'ApotekerController@obatEdit');
    Route::get('/obat-hapus/{obat_id}', 'ApotekerController@obatHapus');

});

Route::group(['prefix' => 'resepsionis'], function () {
    Route::get('/', 'ResepsionisController@index');
    #
    Route::get('/ortu', 'ResepsionisController@ortu');
    Route::match(array('GET', 'POST'), '/ortu-tambah', 'ResepsionisController@ortuTambah');
    Route::match(array('GET', 'POST'), '/ortu-edit/{id}', 'ResepsionisController@ortuEdit');
    Route::get('/ortu-hapus/{id}', 'ResepsionisController@ortuHapus');
    #
    Route::get('/pasien/{ortu_id}', 'ResepsionisController@pasien');
    Route::match(array('GET', 'POST'), '/pasien-tambah/{ortu_id}', 'ResepsionisController@pasienTambah');
    Route::match(array('GET', 'POST'), '/pasien-edit/{ortu_id}/{pasien_id}', 'ResepsionisController@pasienEdit');
    Route::get('/pasien-hapus/{ortu_id}/{pasien_id}', 'ResepsionisController@pasienHapus');
    #
    Route::get('/antrian', 'ResepsionisController@antrian');
    Route::get('/antrian-ajax', 'ResepsionisController@antrianAjax');
    Route::get('/tambah-data-antrian/{pasien_id}/{jenis}/{tgl_antrian}', 'ResepsionisController@antrianTambahData');
    Route::get('/set-diperiksa/{antrian_id}', 'ResepsionisController@antrianSetDiperiksa');
    Route::post('/simpan-antropometri', 'ResepsionisController@simpanAntropometri');
    Route::get('/data-pasien-json', 'ResepsionisController@dataPasienJson');
    Route::get('/data-pasien-dilewati-json', 'ResepsionisController@dataPasienDilewatiJson');
    Route::get('/set-lewati/{antrian_id}', 'ResepsionisController@antrianSetDilewati');
    Route::get('/masukkan-kembali-data-antrian-dilewati/{antrian_id}', 'ResepsionisController@masukkanKembaliPasienDilewati');

    #
    Route::match(array('GET', 'POST'), '/profile', 'ResepsionisController@profile');
    #
    Route::get('/get-nama-pasien', 'ResepsionisController@getNamaPasien');

});

Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'AdminController@index');
    #
    Route::get('/pengguna', 'AdminController@pengguna');
    Route::match(array('GET', 'POST'), '/pengguna-tambah', 'AdminController@penggunaTambah');
    Route::match(array('GET', 'POST'), '/pengguna-edit/{id}', 'AdminController@penggunaEdit');
    Route::get('/pengguna-hapus/{pengguna_id}', 'AdminController@penggunaHapus');
    #
    Route::match(array('GET', 'POST'), '/laporan-grafik', 'AdminController@laporanGrafik');
    Route::match(array('GET', 'POST'), '/laporan-imunisasi', 'AdminController@laporanImunisasi');
    Route::match(array('GET', 'POST'), '/laporan-pemeriksaan', 'AdminController@laporanPemeriksaan');
    Route::match(array('GET', 'POST'), '/laporan-pasien', 'AdminController@laporanPasien');
    Route::match(array('GET', 'POST'), '/laporan-kesesuaian-imunisasi', 'AdminController@laporanKesesuaianImunisasi');

    #
    Route::match(array('GET', 'POST'), '/profile', 'AdminController@profile');

    #

});

Route::group(['prefix' => 'webview'], function () {
    // Route::get('/jadwal-imunisasi', 'WebViewController@jadwalImunisasi');
    // Route::get('/perkembangan-anak', 'WebViewController@perkembanganAnak');
    Route::get('/grafik-bb', 'WebViewController@grafikBb');
    Route::get('/grafik-tb', 'WebViewController@grafikTb');
    Route::get('/grafik-lk', 'WebViewController@grafikLk');
    Route::get('/daftar-notifikasi-antrian', 'WebViewController@daftarNotifikasiAntrian');
});

Route::get('/notifikasi-antrian', 'CronjobController@notifikasiAntrian');

app/Pasien.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Pasien extends Model
{
    //
    protected $table    = 'pasien';
    protected $fillable = [
    	'ortu_id',
        'nama',
        'jk',
        'tempat_lahir',
        'tgl_lahir',
        'foto'
    ];

    public function ortu(){
    	return $this->belongsTo('App\Ortu','ortu_id','id');
    }

    public function getUsiaAttribute(){
        //return $this->nama;
        $start = new Carbon($this->tgl_lahir);
        $end = Carbon::now();
        return $end->diffInMonths($start) . ' Bulan';
    }
}

resources/views/admin/index.blade.php
@extends('admin.layout')
@section('content')
@endsection

resources/views/admin/laporan_grafik.blade.php
@extends('admin.layout')
@section('content')
<script type="text/javascript" src="{{ URL::to('jqplot/jquery.jqplot.min.js') }}"></script>
<script type="text/javascript" src="{{ URL::to('jqplot/plugins/jqplot.barRenderer.js') }}"></script>
<script type="text/javascript" src="{{ URL::to('jqplot/plugins/jqplot.pieRenderer.js') }}"></script>
<script type="text/javascript" src="{{ URL::to('jqplot/plugins/jqplot.categoryAxisRenderer.js') }} "></script>
<script type="text/javascript" src="{{ URL::to('jqplot/plugins/jqplot.pointLabels.js') }}"></script>
<link rel="stylesheet" type="text/css" href="{{ URL::to('jqplot/jquery.jqplot.min.css') }}" />
<!-- Content Header (Page header) -->
<section class="content-header">
   <div class="container-fluid">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h1>Laporan Grafik</h1>
         </div>
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
               <li class="breadcrumb-item"><a href="{{ URL::to('/admin') }}">Home</a></li>
               <li class="breadcrumb-item active"><a href="{{ URL::to('/admin/laporan-grafik') }}">Laporan Bulanan</a></li>
            </ol>
         </div>
      </div>
   </div>
   <!-- /.container-fluid -->
</section>
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">
            <div class="card card-primary">
               <div class="card-header">
                  <h3 class="card-title">Laporan Bulanan</h3>
               </div>
               <!-- /.card-header -->
               <!-- form start -->
               <form role="form" method="POST" action="{{ URL::to('/admin/laporan-grafik') }}">
                  {{ csrf_field() }}
                  <div class="card-body">
                     <div class="form-group">
                        <label>Tahun</label>
                        <select class="form-control" name="tahun" id="tahun">
                        @for($i = 2019; $i <= $tahun_sekarang;$i++)
                        <option value="{{ $i }}" {{ ($tahun_sekarang == $i) ? 'selected' : '' }}>{{ $i }}</option>
                        @endfor
                        </select>
                        @if($errors->has('level'))
                        <div class="text-danger">
                           {{ $errors->first('level')}}
                        </div>
                        @endif                    
                     </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                     <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
               </form>
               
               <div id="chart2"></div>
               
               <!-- /.card -->
            </div>
         </div>
      </div>
   </div>
</section>
<script type="text/javascript">



      $(document).ready(function(){
      @php ($s1 = "")
      @php ($s2 = "")
      @php ($bulan = "")
      
      @foreach ($data as $d)
         @php ($s1 .= $d->jml_imunisasi . ',')
         @php ($s2 .= $d->jml_pemeriksaan . ',')
         @php ($bulan .= "'" . $d->nama . "',")
      @endforeach	
      
         var s1 = [{!! substr($s1,0,-1) !!}];
         var s2 = [{!! substr($s2,0,-1) !!}];
         var ticks = [{!!substr($bulan,0,-1) !!}];
         
         plot2 = $.jqplot('chart2', [s1, s2], {
            title:'Jumlah pasien Imunisasi & Pemeriksaan tahun {{ $tahun_sekarang }}',
            series:[
               { label: 'Imunisasi' },
               { label: 'Pemeriksaan' }
            ], 
            seriesColors: ["#5499C7", "#F4D03F"],
            seriesDefaults: {
                  renderer:$.jqplot.BarRenderer,
                  pointLabels: { show: true },
                  
            },
            
            legend: {
                  renderer: jQuery.jqplot.EnhancedLegendRenderer,
                  show: true, 
                  location: 's', 
                  placement: 'outsideGrid',
                  rendererOptions: {
                     numberRows: '1',
                  },
            },
                  axes: {
                        xaxis: {
                           renderer: $.jqplot.CategoryAxisRenderer,
                           ticks: ticks
                        }
                  }
         });
      
         $('#chart2').bind('jqplotDataHighlight', 
            function (ev, seriesIndex, pointIndex, data) {
               $('#info2').html('series: '+seriesIndex+', point: '+pointIndex+', data: '+data);
            }
         );
            
         $('#chart2').bind('jqplotDataUnhighlight', 
            function (ev) {
               $('#info2').html('Nothing');
            }
         );
      });


   
</script>
@endsection

resources/views/admin/laporan_imunisasi.blade.php
@extends('admin.layout')
@section('content')

<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<!-- Content Header (Page header) -->
<section class="content-header">
   <div class="container-fluid">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h1>Laporan bulanan</h1>
         </div>
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
               <li class="breadcrumb-item"><a href="{{ URL::to('/admin') }}">Home</a></li>
               <li class="breadcrumb-item active"><a href="{{ URL::to('/admin/laporan-imunisasi') }}">Laporan Imunisasi</a></li>
            </ol>
         </div>
      </div>
   </div>
   <!-- /.container-fluid -->
</section>
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">
            <ul id="myTabHeader" class="nav nav-pills" style="margin-bottom: 10px;">
               <li class="nav-item">
                  <a href="#imunisasi" class="nav-link active"  id="tab_imunisasi">Laporan Imunisasi</a>
               </li>
               <li class="nav-item">
                  <a href="{{ URL::to('/admin/laporan-kesesuaian-imunisasi') }}" class="nav-link" id="tab_bb_u">Laporan Kesesuaian Jadwal</a>
               </li>
            </ul>
            <div class="tab-content">
               <div class="tab-pane fade show active" id="imunisasi">
                  <div class="card card-primary">
                     <div class="card-header">
                        <h3 class="card-title">Laporan Imunisasi</h3>
                     </div>
                     <!-- /.card-header -->
                     <!-- form start -->
                     <form role="form" method="POST" action="{{ URL::to('/admin/laporan-imunisasi') }}">
                        {{ csrf_field() }}
                        <div class="card-body">
                         
                           <div class="form-group">
                                 <label>Filter Tanggal</label>
                                 <input type="text" name="filter_tgl" class="form-control" value="<?php echo $filter_tgl?>" />
                           </div>
                           <script>
                           $(function() {
                              $('input[name="filter_tgl"]').daterangepicker({
                                 opens: 'left',
                                 locale: {
                                    format: 'YYYY-MM-DD',
                                    separator: " s/d ",
                                 }
                              }, function(start, end, label) {
                                 console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
                              });
                           });
                           </script>

                          
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                           <button type="submit" name="btnImunisasi" class="btn btn-primary">Submit</button>
                        </div>
                     </form>
                  </div>
                  
                  <ul id="myTab" class="nav nav-pills">
                     <li class="nav-item">
                        <a href="#detail" class="nav-link active"  id="tab_detail">Detail</a>
                     </li>
                     <li class="nav-item">
                        <a href="#group" class="nav-link" id="tab_group">Rekap</a>
                     </li>
                  </ul>
                  <div class="tab-content">
                     <div class="tab-pane fade show active" id="detail">
                        <table id="dataTablesDetail" class="table table-bordered table-striped">
                           <thead>
                              <tr>
                                 <th>Nama</th>
                                 <th>Tanggal</th>
                                 <th>Jenis</th>
                                 <th>Gender</th>
                                 <th>Usia (Bulan)</th>
                                 <!-- <th>Resep</th>
                                 <th>Keterangan</th> -->
                              </tr>
                           </thead>
                           <tbody>
                              @foreach($data as $o)
                              <tr>
                                 <td>{{ $o->nama_pasien }}</td>
                                 <td>{{ $o->tgl }}</td>
                                 <td>{{ $o->nama_imunisasi }}</td>
                                 <td>{{ $o->jk }}</td>
                                 <td>{{ $o->usia }}</td>
                                 <!-- <td>{{ $o->resep }}</td>
                                 <td>{{ $o->keterangan }}</td> -->
                              </tr>
                              @endforeach
                           </tbody>
                        </table>
                     </div>
                     <div class="tab-pane fade" id="group">
                        <table id="dataTablesGroup" class="table table-bordered table-striped">
                           <thead>
                              <tr>
                                 <th>Jenis</th>
                                 <th>Jumlah Pasien</th>
                              </tr>
                           </thead>
                           <tbody>
                              @foreach($imunisasi as $im)
                              <tr>
                                 <td>{{ $im->jenis }}</td>
                                 <td>{{ $im->jml }}</td>
                              </tr>
                              @endforeach
                           </tbody>
                        </table>
                     </div>
                  </div>
                  
               </div>
               
               
               



            </div>
         </div>
      </div>
   </div>
</section>

<script>
    $("#myTab a").click(function(e){
        $(this).tab('show');
    });

 

   $(function () {
     
     $('#dataTablesDetail').DataTable({
       "paging": true,
       "lengthChange": false,
       "searching": true,
       "ordering": true,
       "info": true,
       "autoWidth": false,
       "responsive": true,
     });

     $('#dataTablesGroup').DataTable({
       "paging": true,
       "lengthChange": false,
       "searching": true,
       "ordering": true,
       "info": true,
       "autoWidth": false,
       "responsive": true,
     });
   });
</script>

@endsection

resources/views/admin/laporan_kesesuaian_imunisasi.blade.php
@extends('admin.layout')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
   <div class="container-fluid">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h1>Laporan bulanan</h1>
         </div>
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
               <li class="breadcrumb-item"><a href="{{ URL::to('/admin') }}">Home</a></li>
               <li class="breadcrumb-item active"><a href="{{ URL::to('/admin/laporan-imunisasi') }}">Laporan Imunisasi</a></li>
            </ol>
         </div>
      </div>
   </div>
   <!-- /.container-fluid -->
</section>
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">
            <ul id="myTabHeader" class="nav nav-pills" style="margin-bottom: 10px;">
               <li class="nav-item">
                  <a href="{{ URL::to('/admin/laporan-imunisasi') }}"  class="nav-link" id="tab_imunisasi">Laporan Imunisasi</a>
               </li>
               <li class="nav-item">
                  <a href="#kesesuaian" class="nav-link active" id="tab_bb_u">Laporan Kesesuaian Jadwal</a>
               </li>
            </ul>
            <div class="tab-content">
               
               
               <div class="tab-pane fade show active" id="kesesuaian">
                  <div class="card card-primary">
                     <div class="card-header">
                        <h3 class="card-title">Laporan Kesesuaian Imunisasi</h3>
                     </div>
                     <!-- /.card-header -->
                     <!-- form start -->
                     <form role="form" method="POST" action="{{ URL::to('/admin/laporan-kesesuaian-imunisasi') }}">
                        {{ csrf_field() }}
                        <div class="card-body">
                           
                           <div class="form-group">
                              <label>Filter</label>
                              <select class="form-control" name="filter">
                                 <!-- <option value="SEMUA" {{ $filter === "SEMUA" ? 'selected' : '' }}>Januari</option> -->
                                 <option value="SESUAI" {{ $filter  === "SESUAI" ? 'selected' : '' }}>Sesuai</option>
                                 <option value="TIDAK-SESUAI" {{ $filter  == "TIDAK-SESUAI" ? 'selected' : '' }}>Tidak Sesuai</option>                              
                              </select>
                           </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                           <button type="submit" name="btnImunisasi" class="btn btn-primary">Submit</button>
                        </div>
                     </form>
                  </div>
                  
                  
                     <div class="tab-pane fade show active" id="detail">
                        <table id="dataTablesDetail" class="table table-bordered table-striped">
                           <thead>
                              <tr>
                                 <th>Nama</th>
                                 <th>Usia</th>
                                 <th>Imunisasi</th>                                 
                              </tr>
                           </thead>
                           <tbody>
                              @foreach($data as $o)
                              <tr>
                                 <td>{{ $o['pasien'] }}</td>
                                 <td>{{ $o['usia'] . ' Bulan'}}</td>
                                 <td>{{ $o['imunisasi'] }}</td>                                 
                              </tr>
                              @endforeach
                           </tbody>
                        </table>
                     </div>
                     
                  </div>
                  
               </div>



            </div>
         </div>
      </div>
   </div>
</section>

<script>

   $(function () {
     
     $('#dataTablesDetail').DataTable({
       "paging": true,
       "lengthChange": false,
       "searching": true,
       "ordering": true,
       "info": true,
       "autoWidth": false,
       "responsive": true,
     });


   });
</script>

@endsection

resources/views/admin/laporan_pasien.blade.php
@extends('admin.layout')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
   <div class="container-fluid">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h1>Laporan bulanan</h1>
         </div>
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
               <li class="breadcrumb-item"><a href="{{ URL::to('/admin') }}">Home</a></li>
               <li class="breadcrumb-item active"><a href="{{ URL::to('/admin/laporan-pasien') }}">Laporan Pasien</a></li>
            </ol>
         </div>
      </div>
   </div>
   <!-- /.container-fluid -->
</section>
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">

            <div class="card card-primary">
               <div class="card-header">
                  <h3 class="card-title">Laporan Pasien</h3>
               </div>
               <!-- /.card-header -->
               <!-- form start -->
               <form role="form" method="POST" action="{{ URL::to('/admin/laporan-pasien') }}">
                  {{ csrf_field() }}
                  <div class="card-body">
                     
                     <div class="form-group">
                        <label>Status</label>
                        <select class="form-control" name="status">
                           <option value="semua" {{ $status === 'semua' ? 'selected' : '' }}>Semua</option>
                           <option value="aktif" {{ $status === 'aktif' ? 'selected' : '' }}>Pasien Aktif</option>
                           <option value="tidak-aktif" {{ $status === 'tidak-aktif' ? 'selected' : '' }}>Pasien Tidak Aktif</option>                           
                        </select>
                     </div>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                     <button type="submit" name="btnImunisasi" class="btn btn-primary">Submit</button>
                  </div>
               </form>
            </div>
            
            
               <table id="dataTables" class="table table-bordered table-striped">                        
                  <thead>
                     <tr>
                        <th>Nama</th>
                        <th>Orangtua</th>
                        <th>Kunjungan terakhir</th>
                        <th>Status</th>                        
                     </tr>
                  </thead>
                  <tbody>
                     @foreach($data as $o)
                     <tr>
                        <td>{{ $o->nama }}</td>
                        <td>{{ $o->orangtua }}</td>
                        <td>{{ $o->tgl_terakhir . ' (' . $o->date_diff . ' hari yang lalu)' }}</td>
                        <!-- <td>{{ $o->status }}</td>                         -->
                        @if($o->status === 'AKTIF')
                        <td><span class="badge badge-success">AKTIF</span></td>
                        @else
                        <td><span class="badge badge-warning">TIDAK AKTIF</span></td>
                        @endif 
                     </tr>
                     @endforeach
                  </tbody>
               </table>
             
         </div>
      </div>
   </div>
</section>

<script>

   $(function () {
     
     $('#dataTablesDetail').DataTable({
       "paging": true,
       "lengthChange": false,
       "searching": true,
       "ordering": true,
       "info": true,
       "autoWidth": false,
       "responsive": true,
     });

    
   });
</script>

@endsection

resources/views/admin/laporan_pemeriksaan.blade.php
@extends('admin.layout')
@section('content')

<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

<!-- Content Header (Page header) -->
<section class="content-header">
   <div class="container-fluid">
      <div class="row mb-2">
         <div class="col-sm-6">
            <h1>Laporan Pemeriksaan</h1>
         </div>
         <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
               <li class="breadcrumb-item"><a href="{{ URL::to('/admin') }}">Home</a></li>
               <li class="breadcrumb-item active"><a href="{{ URL::to('/admin/laporan-pemeriksaan') }}">Laporan Pemeriksaan</a></li>
            </ol>
         </div>
      </div>
   </div>
   <!-- /.container-fluid -->
</section>
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">

            <div class="card card-primary">
               <div class="card-header">
                  <h3 class="card-title">Laporan Pemeriksaan</h3>
               </div>
               <!-- /.card-header -->
               <!-- form start -->
               <form role="form" method="POST" action="{{ URL::to('/admin/laporan-pemeriksaan') }}">
                  {{ csrf_field() }}
                  <div class="card-body">
                     <div class="form-group">
                                 <label>Filter Tanggal</label>
                                 <input type="text" name="filter_tgl" class="form-control" value="<?php echo $filter_tgl?>" />
                     </div>
                     <script>
                     $(function() {
                        $('input[name="filter_tgl"]').daterangepicker({
                           opens: 'left',
                           locale: {
                              format: 'YYYY-MM-DD',
                              separator: " s/d ",
                           }
                        }, function(start, end, label) {
                           console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
                        });
                     });
                     </script>
                  </div>
                  <!-- /.card-body -->
                  <div class="card-footer">
                     <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
               </form>
            </div>
            
            
            <table id="dataTables" class="table table-bordered table-striped">                        
               <thead>
                   <tr>
                     <th>Nama</th>
                     <th>Tanggal</th>
                     <th>Anamnesa</th>
                     <th>Gender</th>
                     <th>Usia (Bulan)</th>
                     <!-- <th>Diagnosa</th>
                     <th>Tindakan</th>                              
                     <th>Resep</th>                               -->
                   </tr>
               </thead>
               <tbody>
                   @foreach($data as $o)
                   <tr>
                     <td>{{ $o->nama_pasien }}</td>
                     <td>{{ $o->tgl }}</td>
                     <td>{{ $o->anamnesa }}</td>
                     <td>{{ $o->jk }}</td>
                     <td>{{ $o->usia }}</td>
                     <!-- <td>{{ $o->diagnosa }}</td>
                     <td>{{ $o->tindakan }}</td>                              
                     <td>{{ $o->resep }}</td>                               -->
                   </tr>
                   @endforeach
               </tbody>
             </table>
             
         </div>
      </div>
   </div>
</section>

<script>
   $(function () {
     
     $('#dataTables').DataTable({
       "paging": true,
       "lengthChange": false,
       "searching": true,
       "ordering": true,
       "info": true,
       "autoWidth": false,
       "responsive": true,
     });
   });
</script>

@endsection